version: '3'

services:
  frontend:
    image: gcr.io/topic-chat/frontend:latest
    environment:
      FRONTEND_PORT: 8080
      FRONTEND_LISTEN_ADDR: 0.0.0.0
      TOPIC_CATALOG_SERVICE_ADDR: topic_catalog:8081
      AUTH_SERVICE_ADDR: auth:8082
      DEBUG: "on"
    ports:
      - 8080:8080
  topic_catalog:
    image: gcr.io/topic-chat/topic_catalog:latest
    environment:
      TOPIC_CATALOG_SERVICE_PORT: 8081
      DEBUG: "on"
    ports:
      - 8081:8081
  auth:
    image: gcr.io/topic-chat/auth:latest
    environment:
      AUTH_SERVICE_PORT: 8082
      DEBUG: "on"
    ports:
      - 8082:8082
  chat:
    image: gcr.io/topic-chat/chat:latest
    environment:
      CHAT_SERVICE_PORT: 8083
      DEBUG: "on"
    ports:
      - 8083:8083
  envoy:
    build:
      context: docker/envoy
    ports:
      - 9090:9090
    links:
      - chat
