// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/topicchat.proto

package topicchat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LoggedIn             bool     `protobuf:"varint,3,opt,name=loggedIn,proto3" json:"loggedIn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetLoggedIn() bool {
	if m != nil {
		return m.LoggedIn
	}
	return false
}

type Topic struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{2}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JoinRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{3}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoggedInRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoggedInRequest) Reset()         { *m = LoggedInRequest{} }
func (m *LoggedInRequest) String() string { return proto.CompactTextString(m) }
func (*LoggedInRequest) ProtoMessage()    {}
func (*LoggedInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{4}
}

func (m *LoggedInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggedInRequest.Unmarshal(m, b)
}
func (m *LoggedInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggedInRequest.Marshal(b, m, deterministic)
}
func (m *LoggedInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggedInRequest.Merge(m, src)
}
func (m *LoggedInRequest) XXX_Size() int {
	return xxx_messageInfo_LoggedInRequest.Size(m)
}
func (m *LoggedInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggedInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoggedInRequest proto.InternalMessageInfo

func (m *LoggedInRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SignoutRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignoutRequest) Reset()         { *m = SignoutRequest{} }
func (m *SignoutRequest) String() string { return proto.CompactTextString(m) }
func (*SignoutRequest) ProtoMessage()    {}
func (*SignoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{5}
}

func (m *SignoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignoutRequest.Unmarshal(m, b)
}
func (m *SignoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignoutRequest.Marshal(b, m, deterministic)
}
func (m *SignoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignoutRequest.Merge(m, src)
}
func (m *SignoutRequest) XXX_Size() int {
	return xxx_messageInfo_SignoutRequest.Size(m)
}
func (m *SignoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignoutRequest proto.InternalMessageInfo

func (m *SignoutRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ChatMessage struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{6}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ChatMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Room struct {
	TopicId              int32    `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{7}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetTopicId() int32 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

type CreateRoomRequest struct {
	TopicId              int32    `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{8}
}

func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

func (m *CreateRoomRequest) GetTopicId() int32 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

type RecvMessageRequest struct {
	TopicId              int32    `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecvMessageRequest) Reset()         { *m = RecvMessageRequest{} }
func (m *RecvMessageRequest) String() string { return proto.CompactTextString(m) }
func (*RecvMessageRequest) ProtoMessage()    {}
func (*RecvMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{9}
}

func (m *RecvMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecvMessageRequest.Unmarshal(m, b)
}
func (m *RecvMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecvMessageRequest.Marshal(b, m, deterministic)
}
func (m *RecvMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecvMessageRequest.Merge(m, src)
}
func (m *RecvMessageRequest) XXX_Size() int {
	return xxx_messageInfo_RecvMessageRequest.Size(m)
}
func (m *RecvMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecvMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecvMessageRequest proto.InternalMessageInfo

func (m *RecvMessageRequest) GetTopicId() int32 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *RecvMessageRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SendMessageRequest struct {
	TopicId              int32        `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Message              *ChatMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{10}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetTopicId() int32 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *SendMessageRequest) GetMessage() *ChatMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type ListRoomResponse struct {
	Rooms                []*Room  `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRoomResponse) Reset()         { *m = ListRoomResponse{} }
func (m *ListRoomResponse) String() string { return proto.CompactTextString(m) }
func (*ListRoomResponse) ProtoMessage()    {}
func (*ListRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{11}
}

func (m *ListRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoomResponse.Unmarshal(m, b)
}
func (m *ListRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoomResponse.Marshal(b, m, deterministic)
}
func (m *ListRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoomResponse.Merge(m, src)
}
func (m *ListRoomResponse) XXX_Size() int {
	return xxx_messageInfo_ListRoomResponse.Size(m)
}
func (m *ListRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoomResponse proto.InternalMessageInfo

func (m *ListRoomResponse) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type ListTopicsResponse struct {
	Topics               []*Topic `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTopicsResponse) Reset()         { *m = ListTopicsResponse{} }
func (m *ListTopicsResponse) String() string { return proto.CompactTextString(m) }
func (*ListTopicsResponse) ProtoMessage()    {}
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{12}
}

func (m *ListTopicsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTopicsResponse.Unmarshal(m, b)
}
func (m *ListTopicsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTopicsResponse.Marshal(b, m, deterministic)
}
func (m *ListTopicsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTopicsResponse.Merge(m, src)
}
func (m *ListTopicsResponse) XXX_Size() int {
	return xxx_messageInfo_ListTopicsResponse.Size(m)
}
func (m *ListTopicsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTopicsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTopicsResponse proto.InternalMessageInfo

func (m *ListTopicsResponse) GetTopics() []*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

type GetTopicRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicRequest) Reset()         { *m = GetTopicRequest{} }
func (m *GetTopicRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopicRequest) ProtoMessage()    {}
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c4a8088c4bf324, []int{13}
}

func (m *GetTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicRequest.Unmarshal(m, b)
}
func (m *GetTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicRequest.Marshal(b, m, deterministic)
}
func (m *GetTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicRequest.Merge(m, src)
}
func (m *GetTopicRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopicRequest.Size(m)
}
func (m *GetTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicRequest proto.InternalMessageInfo

func (m *GetTopicRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "topicchat.Empty")
	proto.RegisterType((*User)(nil), "topicchat.User")
	proto.RegisterType((*Topic)(nil), "topicchat.Topic")
	proto.RegisterType((*JoinRequest)(nil), "topicchat.JoinRequest")
	proto.RegisterType((*LoggedInRequest)(nil), "topicchat.LoggedInRequest")
	proto.RegisterType((*SignoutRequest)(nil), "topicchat.SignoutRequest")
	proto.RegisterType((*ChatMessage)(nil), "topicchat.ChatMessage")
	proto.RegisterType((*Room)(nil), "topicchat.Room")
	proto.RegisterType((*CreateRoomRequest)(nil), "topicchat.CreateRoomRequest")
	proto.RegisterType((*RecvMessageRequest)(nil), "topicchat.RecvMessageRequest")
	proto.RegisterType((*SendMessageRequest)(nil), "topicchat.SendMessageRequest")
	proto.RegisterType((*ListRoomResponse)(nil), "topicchat.ListRoomResponse")
	proto.RegisterType((*ListTopicsResponse)(nil), "topicchat.ListTopicsResponse")
	proto.RegisterType((*GetTopicRequest)(nil), "topicchat.GetTopicRequest")
}

func init() { proto.RegisterFile("pb/topicchat.proto", fileDescriptor_f7c4a8088c4bf324) }

var fileDescriptor_f7c4a8088c4bf324 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0xc7, 0x9b, 0xae, 0x2f, 0xd9, 0x89, 0xb4, 0xee, 0x39, 0x8f, 0x04, 0x5d, 0x60, 0x52, 0x6b,
	0x84, 0x54, 0x40, 0x2a, 0xa3, 0xdc, 0x30, 0x90, 0x8a, 0x50, 0x45, 0x51, 0xd1, 0xb8, 0x49, 0xc7,
	0x35, 0xca, 0x1a, 0x2b, 0x8d, 0xb4, 0xc4, 0x21, 0x76, 0x27, 0xf8, 0x1a, 0x7c, 0x17, 0xbe, 0x1f,
	0xb2, 0x13, 0xa7, 0x6e, 0x52, 0x58, 0xef, 0x62, 0x9f, 0xff, 0xf9, 0x9f, 0x17, 0xff, 0x5a, 0xc0,
	0xf4, 0xe6, 0xa5, 0x60, 0x69, 0xb4, 0x5a, 0xad, 0x7d, 0x31, 0x4e, 0x33, 0x26, 0x18, 0x1e, 0x97,
	0x17, 0xa4, 0x0b, 0xed, 0x8f, 0x71, 0x2a, 0x7e, 0x92, 0x39, 0xb4, 0xbe, 0x72, 0x9a, 0xe1, 0x09,
	0x34, 0xa3, 0xa0, 0x6f, 0x0d, 0xac, 0xd1, 0xb1, 0xd7, 0x8c, 0x02, 0x44, 0x68, 0x25, 0x7e, 0x4c,
	0xfb, 0x4d, 0x75, 0xa3, 0xbe, 0xd1, 0x05, 0xfb, 0x96, 0x85, 0x21, 0x0d, 0x16, 0x49, 0xff, 0x68,
	0x60, 0x8d, 0x6c, 0xaf, 0x3c, 0x93, 0x17, 0xd0, 0xbe, 0x96, 0xee, 0x87, 0x18, 0x91, 0x21, 0x38,
	0x9f, 0x59, 0x94, 0x78, 0xf4, 0xfb, 0x86, 0x72, 0x51, 0x4a, 0x2c, 0x43, 0xf2, 0x1c, 0x7a, 0x57,
	0x85, 0xb7, 0x96, 0x3d, 0x84, 0xee, 0x86, 0xd3, 0xec, 0x5b, 0x69, 0xdf, 0x91, 0xc7, 0x45, 0x40,
	0x9e, 0xc1, 0xc9, 0x32, 0x0a, 0x13, 0xb6, 0x11, 0xf7, 0x4a, 0xe7, 0xe0, 0xcc, 0xd6, 0xbe, 0xf8,
	0x42, 0x39, 0xf7, 0x43, 0x2a, 0x2b, 0x0b, 0xfa, 0x43, 0xe8, 0xca, 0xf2, 0x1b, 0x9f, 0x40, 0x4b,
	0x8a, 0x55, 0xc3, 0xce, 0xa4, 0x37, 0xde, 0x6e, 0x51, 0x2e, 0xca, 0x53, 0x41, 0x32, 0x84, 0x96,
	0xc7, 0x58, 0x8c, 0x67, 0x60, 0xab, 0xb8, 0xae, 0xd4, 0xf6, 0xba, 0xea, 0xbc, 0x08, 0xc8, 0x18,
	0xfe, 0x9b, 0x65, 0xd4, 0x17, 0x54, 0x0a, 0x75, 0x63, 0xff, 0xd0, 0x5f, 0x03, 0x7a, 0x74, 0x75,
	0x57, 0xb4, 0x76, 0x7f, 0xc2, 0x61, 0x8d, 0xfa, 0x80, 0x4b, 0x9a, 0x04, 0x87, 0xbb, 0x5e, 0x40,
	0x37, 0xce, 0xc5, 0x85, 0xf1, 0x03, 0xc3, 0xd8, 0xd8, 0x9d, 0xa7, 0x65, 0xe4, 0x12, 0x4e, 0xaf,
	0x22, 0x2e, 0xf2, 0x31, 0x79, 0xca, 0x12, 0x4e, 0xf1, 0x29, 0xb4, 0x33, 0xc6, 0x62, 0xde, 0xb7,
	0x06, 0x47, 0x95, 0xe6, 0x94, 0x2e, 0x8f, 0x92, 0x29, 0xa0, 0x4c, 0x55, 0xe4, 0xf0, 0x32, 0x79,
	0x04, 0x1d, 0x25, 0xd7, 0xd9, 0xa7, 0x46, 0xb6, 0x92, 0x7a, 0x45, 0x9c, 0x0c, 0xa1, 0xf7, 0x89,
	0xe6, 0xe9, 0x7a, 0xb4, 0x0a, 0x7f, 0x93, 0xdf, 0x16, 0x38, 0x1f, 0x36, 0x62, 0xbd, 0xa4, 0xd9,
	0x5d, 0xb4, 0xa2, 0xf8, 0x0a, 0x5a, 0x92, 0x3d, 0x34, 0xc7, 0x32, 0x60, 0x74, 0xab, 0x7b, 0x24,
	0x0d, 0xbc, 0x04, 0x5b, 0xb3, 0x88, 0xae, 0x11, 0xae, 0x00, 0xba, 0x2f, 0xf5, 0x0d, 0x74, 0x0b,
	0x34, 0xf1, 0xcc, 0x88, 0xee, 0xe2, 0xea, 0x9a, 0x03, 0xe6, 0x3f, 0xcb, 0xc6, 0xe4, 0x57, 0x33,
	0x47, 0x55, 0xf7, 0x3d, 0x07, 0xc7, 0xc0, 0x03, 0xcf, 0xcd, 0x8d, 0xd6, 0xb0, 0x71, 0xff, 0xf2,
	0x68, 0x17, 0x16, 0x4e, 0xc1, 0x31, 0x80, 0xd8, 0xf1, 0xa9, 0x83, 0x52, 0xef, 0x0c, 0xa7, 0x00,
	0x5b, 0xac, 0xf1, 0xb1, 0x59, 0xa7, 0x4a, 0xfb, 0xbe, 0xb9, 0xf0, 0x1d, 0xd8, 0x9a, 0x16, 0xac,
	0xc5, 0xdd, 0x47, 0xe6, 0x7a, 0x2b, 0x50, 0xc9, 0xa5, 0x58, 0xf0, 0xbf, 0x7a, 0xed, 0x99, 0x2f,
	0xfc, 0x5b, 0x16, 0xea, 0xe5, 0xbc, 0x07, 0xd8, 0x72, 0xb4, 0xc7, 0xf6, 0xbc, 0x62, 0xbb, 0x0b,
	0x1c, 0x69, 0xe0, 0x5b, 0xb0, 0x35, 0x48, 0x3b, 0x4f, 0x5c, 0xa1, 0xcb, 0xad, 0xa1, 0x48, 0x1a,
	0x37, 0x1d, 0xf5, 0xef, 0xfa, 0xfa, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x15, 0x50, 0x9b,
	0x73, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*User, error)
	LoggedIn(ctx context.Context, in *LoggedInRequest, opts ...grpc.CallOption) (*User, error)
	Signout(ctx context.Context, in *SignoutRequest, opts ...grpc.CallOption) (*Empty, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/topicchat.AuthService/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LoggedIn(ctx context.Context, in *LoggedInRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/topicchat.AuthService/LoggedIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Signout(ctx context.Context, in *SignoutRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/topicchat.AuthService/Signout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Join(context.Context, *JoinRequest) (*User, error)
	LoggedIn(context.Context, *LoggedInRequest) (*User, error)
	Signout(context.Context, *SignoutRequest) (*Empty, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Join(ctx context.Context, req *JoinRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedAuthServiceServer) LoggedIn(ctx context.Context, req *LoggedInRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoggedIn not implemented")
}
func (*UnimplementedAuthServiceServer) Signout(ctx context.Context, req *SignoutRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signout not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicchat.AuthService/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LoggedIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoggedInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LoggedIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicchat.AuthService/LoggedIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LoggedIn(ctx, req.(*LoggedInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Signout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Signout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicchat.AuthService/Signout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Signout(ctx, req.(*SignoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topicchat.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _AuthService_Join_Handler,
		},
		{
			MethodName: "LoggedIn",
			Handler:    _AuthService_LoggedIn_Handler,
		},
		{
			MethodName: "Signout",
			Handler:    _AuthService_Signout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/topicchat.proto",
}

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	// ---- Message ----
	RecvMessage(ctx context.Context, in *RecvMessageRequest, opts ...grpc.CallOption) (ChatService_RecvMessageClient, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*Empty, error)
	// ---- Room ----
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Empty, error)
	ListRoom(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListRoomResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) RecvMessage(ctx context.Context, in *RecvMessageRequest, opts ...grpc.CallOption) (ChatService_RecvMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatService_serviceDesc.Streams[0], "/topicchat.ChatService/RecvMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceRecvMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_RecvMessageClient interface {
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatServiceRecvMessageClient struct {
	grpc.ClientStream
}

func (x *chatServiceRecvMessageClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/topicchat.ChatService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/topicchat.ChatService/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListRoom(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListRoomResponse, error) {
	out := new(ListRoomResponse)
	err := c.cc.Invoke(ctx, "/topicchat.ChatService/ListRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	// ---- Message ----
	RecvMessage(*RecvMessageRequest, ChatService_RecvMessageServer) error
	SendMessage(context.Context, *SendMessageRequest) (*Empty, error)
	// ---- Room ----
	CreateRoom(context.Context, *CreateRoomRequest) (*Empty, error)
	ListRoom(context.Context, *Empty) (*ListRoomResponse, error)
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) RecvMessage(req *RecvMessageRequest, srv ChatService_RecvMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method RecvMessage not implemented")
}
func (*UnimplementedChatServiceServer) SendMessage(ctx context.Context, req *SendMessageRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedChatServiceServer) CreateRoom(ctx context.Context, req *CreateRoomRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (*UnimplementedChatServiceServer) ListRoom(ctx context.Context, req *Empty) (*ListRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoom not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_RecvMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecvMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).RecvMessage(m, &chatServiceRecvMessageServer{stream})
}

type ChatService_RecvMessageServer interface {
	Send(*ChatMessage) error
	grpc.ServerStream
}

type chatServiceRecvMessageServer struct {
	grpc.ServerStream
}

func (x *chatServiceRecvMessageServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicchat.ChatService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicchat.ChatService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicchat.ChatService/ListRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListRoom(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topicchat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _ChatService_CreateRoom_Handler,
		},
		{
			MethodName: "ListRoom",
			Handler:    _ChatService_ListRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecvMessage",
			Handler:       _ChatService_RecvMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/topicchat.proto",
}

// TopicCatalogServiceClient is the client API for TopicCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopicCatalogServiceClient interface {
	ListTopics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTopicsResponse, error)
	GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*Topic, error)
}

type topicCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTopicCatalogServiceClient(cc grpc.ClientConnInterface) TopicCatalogServiceClient {
	return &topicCatalogServiceClient{cc}
}

func (c *topicCatalogServiceClient) ListTopics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, "/topicchat.TopicCatalogService/ListTopics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicCatalogServiceClient) GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*Topic, error) {
	out := new(Topic)
	err := c.cc.Invoke(ctx, "/topicchat.TopicCatalogService/GetTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopicCatalogServiceServer is the server API for TopicCatalogService service.
type TopicCatalogServiceServer interface {
	ListTopics(context.Context, *Empty) (*ListTopicsResponse, error)
	GetTopic(context.Context, *GetTopicRequest) (*Topic, error)
}

// UnimplementedTopicCatalogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTopicCatalogServiceServer struct {
}

func (*UnimplementedTopicCatalogServiceServer) ListTopics(ctx context.Context, req *Empty) (*ListTopicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopics not implemented")
}
func (*UnimplementedTopicCatalogServiceServer) GetTopic(ctx context.Context, req *GetTopicRequest) (*Topic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopic not implemented")
}

func RegisterTopicCatalogServiceServer(s *grpc.Server, srv TopicCatalogServiceServer) {
	s.RegisterService(&_TopicCatalogService_serviceDesc, srv)
}

func _TopicCatalogService_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicCatalogServiceServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicchat.TopicCatalogService/ListTopics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicCatalogServiceServer).ListTopics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicCatalogService_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicCatalogServiceServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicchat.TopicCatalogService/GetTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicCatalogServiceServer).GetTopic(ctx, req.(*GetTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TopicCatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topicchat.TopicCatalogService",
	HandlerType: (*TopicCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTopics",
			Handler:    _TopicCatalogService_ListTopics_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _TopicCatalogService_GetTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/topicchat.proto",
}
